name: Render PHP Demo Page

on:
  push:
  pull_request:

jobs:
  prerender:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: none

      - name: Pre-render PHP File
        run: |
          cd htdocs
          php ./index.php > ./index.raw.html

      - name: Upload `index.html` build artifact
        uses: actions/upload-artifact@v4
        if: ${{ github.actor == 'aziascreations' }}
        with:
          name: index.html
          path: "./htdocs/index.html"
          if-no-files-found: error
          retention-days: 90
          compression-level: 9
